spring:
  application:
    name: artisa


  datasource:
    url: jdbc:postgresql://localhost:5432/artisa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MySecretKey
  expiration: 3600000
  header: Authorization
  prefix: Bearer



#spring.application.name=artisa
##postgresql settings
#spring.datasource.url=jdbc:postgresql://localhost:5432/artisa
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## JWT settings
#jwt.secret=yourSecretKey
#jwt.expiration=3600000
#jwt.header=Authorization
#jwt.prefix=Bearer
