spring:
  application:
    name: artisa

  datasource:
    url: jdbc:postgresql://localhost:5432/artisa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MySecretKey
  expiration: 3600000
  header: Authorization
  prefix: Bearer

server:
  servlet:
    context-path: /api